### ISSUE TITLE
Please can we add the WasteAware demo to the CIWM hub?

### ISSUE THREAD

**Issue by AnnaHavard** [CIWM/CIWM-Hub#7]

**Comment by nick69g** [comment]
OK. Will get this sorted.

**Comment by nick69g** [comment]
This has been added.

**Comment by AnnaHavard** [comment]
Hi Nick

This doesn’t work properly – the demonstration doesn’t fit in the window properly -

[cid:image003.jpg@01D0CDD3.7B344100]



        Anna Havard
        Client Relationship Manager
        CIWM Enterprises Ltd

Tel:    +44 (0)1604 823347
Fax:    +44 (0)1604 604467
Email:  Anna.Havard@ciwm.co.uk<mailto:Anna.Havard@ciwm.co.uk>
Web:    www.ciwm.co.uk<http://www.ciwm.co.uk>




[cid:imagebc97c4.JPG@9f15da73.44b0eecf]<http://>

[cid:imaged2504d.PNG@cad6a42f.47a0e557]<http://ciwmawards.com>

Inspiring excellence in resource management
As the pre-eminent institution for resource management, CIWM champions the success of individual professionals, organisations, and the sector as a whole. It does this by influencing future legislation and policy, leveraging partnerships, delivering industry insights, providing advice and training, sharing knowledge and recognising outstanding achievements.

Head office: CIWM / CIWM Enterprises Ltd., 9 Saxon Court, St. Peters Gardens, Marefair, Northampton, Northamptonshire. NN1 1SX

CIWM is a company incorporated by Royal Charter. Registered in England No. RC000777. A charity registered in England & Wales (1090968) and in Scotland (SC037903) VAT Reg. no. 232 8003 02. CIWM Enterprises Ltd is a subsidiary company of CIWM Registered in England & Wales No. 2731563 VAT Reg. No. 581 4550 37.

This message is confidential and may be legally privileged or otherwise protected from disclosure. If you are not the intended recipient, please contact the sender and delete this message and any attachment from your system. You must not copy, distribute or disclose the contents of this message or any attachment. Please note that neither CIWM/CIWM Enterprises Ltd nor the sender of this email accepts any responsibility for viruses and it is your responsibility to scan this email and any attachments. Contracts and variations to contracts cannot be concluded on behalf of CIWM or CIWM Enterprises Ltd by means of email.

**Comment by nick69g** [comment]
I was able to resize the window but I've remove the menu to make the module screen smaller (the menu can be opened with a click). I think we've done that with some of the other demos. So it opens and fits OK. You may need to refresh browser/clear cache if you cannot see the change.

**Comment by AnnaHavard** [comment]
Thanks Nick, seems OK now although the menu text is very small. I don’t know what you mean by opening the menu unfortunately.



        Anna Havard
        Client Relationship Manager
        CIWM Enterprises Ltd

Tel:    +44 (0)1604 823347
Fax:    +44 (0)1604 604467
Email:  Anna.Havard@ciwm.co.uk<mailto:Anna.Havard@ciwm.co.uk>
Web:    www.ciwm.co.uk<http://www.ciwm.co.uk>




[cid:image60b8d7.JPG@2a94f761.488e836c]<http://>

[cid:image1e41b7.PNG@75dbb168.4d9ccd14]<http://ciwmawards.com>

Inspiring excellence in resource management
As the pre-eminent institution for resource management, CIWM champions the success of individual professionals, organisations, and the sector as a whole. It does this by influencing future legislation and policy, leveraging partnerships, delivering industry insights, providing advice and training, sharing knowledge and recognising outstanding achievements.

Head office: CIWM / CIWM Enterprises Ltd., 9 Saxon Court, St. Peters Gardens, Marefair, Northampton, Northamptonshire. NN1 1SX

CIWM is a company incorporated by Royal Charter. Registered in England No. RC000777. A charity registered in England & Wales (1090968) and in Scotland (SC037903) VAT Reg. no. 232 8003 02. CIWM Enterprises Ltd is a subsidiary company of CIWM Registered in England & Wales No. 2731563 VAT Reg. No. 581 4550 37.

This message is confidential and may be legally privileged or otherwise protected from disclosure. If you are not the intended recipient, please contact the sender and delete this message and any attachment from your system. You must not copy, distribute or disclose the contents of this message or any attachment. Please note that neither CIWM/CIWM Enterprises Ltd nor the sender of this email accepts any responsibility for viruses and it is your responsibility to scan this email and any attachments. Contracts and variations to contracts cannot be concluded on behalf of CIWM or CIWM Enterprises Ltd by means of email.

**Comment by nick69g** [comment]
Only that you can open the menu by clicking on the link (top left) 
rather that it always showing.

**Comment by nick69g** [comment]
The demonstration has been added to the CIWM Hub and displays and plays correctly.
