### ISSUE TITLE
Peter Smith of Interserve cannot access Waste Expert Learn

### ISSUE THREAD

**Issue by DanielHowells** [CIWM/CIWM-Hub#9]
Hi

I have just purchased a subscription to Waste Expert learn via CIWM.

It shows up on the CIWM my account page however I cannot  login using their link - my password is not recognised and nothing happens when I try reset password.

When I get to your "my account" page it shows no PAYG products.

Please could you resolve this

Many thanks

Peter Smith

**Comment by DanielHowells** [comment]
Afternoon Peter,

Apologies for the login issue you were facing.  I have reset your password to the following:

Password: Pa$$word1

This password will provide you with access to both the CIWM Knowledge Hub and also the Waste Expert.  Could you please check your logins and let me know if you have any further issues.

For the time being could you please refrain from updating your password until will have fixed the problem.

Kind regards

Rob Bresler BSc (Hons), Chartered Waste Manager, AIEMA
Associate Director

**Comment by DanielHowells** [comment]
This was resolved on the day. I have since spoken to Peter twice as follow ups.

**Comment by nick69g** [comment]
A new issue to identify this bug specifically has been raised.
